### ISSUE TITLE
Omission of john command

### ISSUE THREAD

**Issue by TeddeBaer** [Bouni/luxtronik-firmware-analysis#1]
Thank you for helping me with understanding my Luxtronik controlled heatpump!

I copied the lines from your root_password.sh shell script in order to get the root password. I am not familiar to john, but to my understanding there is a john command missing before line 16. Line 16 seems to just show the cracked password. https://github.com/Bouni/luxtronik-firmware-analysis/blob/f7a490aebda5e185bab2f324d1011d2255684d40/root_password.sh#L16

Should there be a line `john unshadow.txt` before line 16?

**Comment by Bouni** [comment]
No, acually `cracked` is a variable that is filled by the command within `$()`, so the command that runs is `john --show unshadow.txt 2> /dev/null | grep root`

I know that the script is broken on Debian/Ubuntu systems because there is some issue with the john command but it works on my Arch linux ...

**Comment by Bouni** [comment]
I've just fixed the script.
Turns out john caches a successfull crack to `~/.john/john.pot`, the `--show` only shows already cracked passwords, in order to crack it in the first place a `--incremental` needed.
